<a href="https://colab.research.google.com/github/audomsak-pypy/PythonDataViz2026/blob/main/HW6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *HW6* 673020271-0 #

### ดึงข้อมูลมาใช้ + ปรับข้อมูลจากคำสั่ง (.fillna)

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path = "/content/drive/MyDrive/DataViz_2026"
covid_file = os.path.join(path,'confirmed-cases.csv')
print(covid_file)

/content/drive/MyDrive/DataViz_2026/confirmed-cases.csv


In [ ]:
data = pd.read_csv(covid_file)
data.head()

/tmp/ipykernel_2031/3129093645.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(covid_file)


,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN


In [ ]:
data_updated = data.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_onset':'ไม่รู้', 'nationality':'ไม่รู้', 'district_of_onset': 'ไม่รู้', 'Notified date': '-', 'Unit': 'ปี'})
data_updated

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,-,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
1,2,17/1/2020,-,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
2,3,22/1/2020,-,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,-,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
4,5,24/1/2020,-,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,ไม่รู้,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่รู้
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่รู้
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่รู้
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่รู้


##HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น
3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

###No.1 คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด

In [ ]:
data_age = data_updated[['sex','age','province_of_onset']]
data_age

,sex,age,province_of_onset
0,หญิง,61.0,กรุงเทพมหานคร
1,หญิง,74.0,กรุงเทพมหานคร
2,หญิง,73.0,นครปฐม
3,ชาย,68.0,กรุงเทพมหานคร
4,หญิง,66.0,กรุงเทพมหานคร
...,...,...,...
839766,ชาย,52.0,กาญจนบุรี
839767,ชาย,34.0,กาญจนบุรี
839768,ชาย,31.0,กาญจนบุรี
839769,ชาย,83.0,กาญจนบุรี


In [ ]:
data_updated[data_updated['age']== -1]

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
484,485,22/3/2020,21/3/2020,ชาย,-1,ปี,Thailand,กรุงเทพมหานคร,สนามมวย,กรุงเทพมหานคร,ไม่รู้
504,505,22/3/2020,21/3/2020,ชาย,-1,ปี,Thailand,กรุงเทพมหานคร,สถานบันเทิง,กรุงเทพมหานคร,ไม่รู้
577,578,22/3/2020,20/3/2020,ชาย,-1,ปี,Thailand,กรุงเทพมหานคร,สนามมวย,ไม่รู้,ไม่รู้
589,590,22/3/2020,21/3/2020,ชาย,-1,ปี,Thailand,กรุงเทพมหานคร,อยู่ระหว่างการสอบสวน,ไม่รู้,ไม่รู้
814,815,24/3/2020,23/3/2020,ชาย,-1,ปี,Thailand,กรุงเทพมหานคร,สนามมวย,ไม่รู้,ไม่รู้
...,...,...,...,...,...,...,...,...,...,...,...
839745,839746,12/8/2021,11/8/2021,ชาย,-1,ปี,ไม่รู้,นราธิวาส,ทัณฑสถาน/เรือนจำ,นราธิวาส,ไม่รู้
839746,839747,12/8/2021,11/8/2021,ชาย,-1,ปี,Thailand,นราธิวาส,ทัณฑสถาน/เรือนจำ,นราธิวาส,ไม่รู้
839747,839748,12/8/2021,11/8/2021,ชาย,-1,ปี,Thailand,นราธิวาส,ทัณฑสถาน/เรือนจำ,นราธิวาส,ไม่รู้
839748,839749,12/8/2021,11/8/2021,ชาย,-1,ปี,Thailand,นราธิวาส,ทัณฑสถาน/เรือนจำ,นราธิวาส,ไม่รู้


In [ ]:
famale = data_age[data_age['sex']=='หญิง']
famale

,sex,age,province_of_onset
0,หญิง,61.0,กรุงเทพมหานคร
1,หญิง,74.0,กรุงเทพมหานคร
2,หญิง,73.0,นครปฐม
4,หญิง,66.0,กรุงเทพมหานคร
5,หญิง,33.0,กรุงเทพมหานคร
...,...,...,...
839737,หญิง,57.0,กาญจนบุรี
839738,หญิง,50.0,กาญจนบุรี
839739,หญิง,37.0,กาญจนบุรี
839740,หญิง,24.0,กาญจนบุรี


In [ ]:
male = data_age[data_age['sex']=='ชาย']
male

,sex,age,province_of_onset
3,ชาย,68.0,กรุงเทพมหานคร
8,ชาย,63.0,กรุงเทพมหานคร
10,ชาย,33.0,กรุงเทพมหานคร
11,ชาย,61.0,กรุงเทพมหานคร
12,ชาย,6.0,กรุงเทพมหานคร
...,...,...,...
839766,ชาย,52.0,กาญจนบุรี
839767,ชาย,34.0,กาญจนบุรี
839768,ชาย,31.0,กาญจนบุรี
839769,ชาย,83.0,กาญจนบุรี


In [ ]:
famale['age'].head()

,age
0,61.0
1,74.0
2,73.0
4,66.0
5,33.0


dtype: object

EX:
0     61.0
1     74.0
2     73.0
...  ข้อมูลยังเป็น String แปลงให้เป็น float (ex:61.0, 74.0, ...)  ก่อนการคำนวน

In [ ]:
famale['age'] =  pd.to_numeric(famale['age'], errors='coerce') #แปลงให้เป็นตัวเลข

/tmp/ipykernel_2031/102803793.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  famale['age'] =  pd.to_numeric(famale['age'], errors='coerce') #แปลงให้เป็นตัวเลข


In [ ]:
male['age'] = pd.to_numeric(male['age'])

/tmp/ipykernel_2031/3593769216.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  male['age'] = pd.to_numeric(male['age'])


In [ ]:
famale_sum = 0
famale_N = 0
for age in famale['age']:
    if age > 0:
        famale_sum += age
        famale_N += 1
print("อายุเฉลี่ยผู้หญิง:", famale_sum / famale_N)

อายุเฉลี่ยผู้หญิง: 36.16090881617699


In [ ]:
male_sum = 0
male_N = 0
for age in male['age']:
    if age > 0:
        male_sum += age
        male_N += 1
print("อายุเฉลี่ยผู้ชาย:",male_sum / male_N)

อายุเฉลี่ยผู้ชาย: 34.962927021309376


###No.2 คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

In [ ]:
famale_KhonKaen = famale[data_age['province_of_onset']=='ขอนแก่น'] #เลือกมาเฉพาะคนที่อยู่ขอนแก่น
famale_KhonKaen

/tmp/ipykernel_2031/2135130357.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  famale_KhonKaen = famale[data_age['province_of_onset']=='ขอนแก่น'] #เลือกมาเฉพาะคนที่อยู่ขอนแก่น


,sex,age,province_of_onset
463,หญิง,36.0,ขอนแก่น
1971,หญิง,70.0,ขอนแก่น
2638,หญิง,63.0,ขอนแก่น
5949,หญิง,32.0,ขอนแก่น
6083,หญิง,36.0,ขอนแก่น
...,...,...,...
839556,หญิง,28.0,ขอนแก่น
839557,หญิง,44.0,ขอนแก่น
839558,หญิง,34.0,ขอนแก่น
839559,หญิง,34.0,ขอนแก่น


In [ ]:
male_KhonKaen = male[data_age['province_of_onset']=='ขอนแก่น']
male_KhonKaen

/tmp/ipykernel_2031/1459433592.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  male_KhonKaen = male[data_age['province_of_onset']=='ขอนแก่น']


,sex,age,province_of_onset
181,ชาย,33.0,ขอนแก่น
1467,ชาย,19.0,ขอนแก่น
2674,ชาย,68.0,ขอนแก่น
9334,ชาย,17.0,ขอนแก่น
9335,ชาย,20.0,ขอนแก่น
...,...,...,...
839669,ชาย,46.0,ขอนแก่น
839670,ชาย,58.0,ขอนแก่น
839671,ชาย,30.0,ขอนแก่น
839672,ชาย,20.0,ขอนแก่น


In [ ]:
famale_sum = 0
famale_N = 0
for age in famale_KhonKaen['age']:
    if age > 0:
        famale_sum += age
        famale_N += 1
print("อายุเฉลี่ยผู้หญิง:", famale_sum / famale_N)

อายุเฉลี่ยผู้หญิง: 34.59362745098039


In [ ]:
male_sum = 0
male_N = 0
for age in male_KhonKaen['age']:
    if age > 0:
        male_sum += age
        male_N += 1
print("อายุเฉลี่ยผู้ชาย:",male_sum / male_N)

อายุเฉลี่ยผู้ชาย: 34.057632398753896


###No.3 หาจำนวนผู้ป่วยที่เป็นคน "คนต่างชาติเดินทางมาจากต่างประเทศ"

In [ ]:
data_drop = data_updated[data_updated['nationality'] != 'Thailand'] #ตัดคนที่เป็นคนสัญชาติไทยออกทั้งหมด
data_drop

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,-,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
1,2,17/1/2020,-,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
3,4,22/1/2020,-,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
4,5,24/1/2020,-,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
5,6,25/1/2020,-,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
...,...,...,...,...,...,...,...,...,...,...,...
839762,839763,12/8/2021,11/8/2021,ชาย,36.0,ปี,ไม่รู้,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่รู้
839763,839764,12/8/2021,11/8/2021,ชาย,64.0,ปี,ไม่รู้,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่รู้
839764,839765,12/8/2021,11/8/2021,ชาย,43.0,ปี,ไม่รู้,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่รู้
839765,839766,12/8/2021,11/8/2021,ชาย,53.0,ปี,ไม่รู้,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,ไม่รู้


In [ ]:
people_entry = data_drop[data_drop['risk'] == 'คนต่างชาติเดินทางมาจากต่างประเทศ']
people_entry

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,-,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
1,2,17/1/2020,-,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
3,4,22/1/2020,-,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
4,5,24/1/2020,-,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
5,6,25/1/2020,-,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
...,...,...,...,...,...,...,...,...,...,...,...
633718,633719,3/8/2021,2/8/2021,ชาย,68.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,ไม่รู้
756541,756542,9/8/2021,8/8/2021,ชาย,30.0,ปี,Burmese,เชียงราย,คนต่างชาติเดินทางมาจากต่างประเทศ,เชียงราย,ไม่รู้
776624,776625,10/8/2021,9/8/2021,หญิง,9.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,แม่ระมาด
776625,776626,10/8/2021,9/8/2021,หญิง,19.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,แม่ระมาด


In [ ]:
print(f"จำนวนคนต่างชาติที่เดินทางมาจากต่างประเทศมี {len(people_entry)} คน")

จำนวนคนต่างชาติที่เดินทางมาจากต่างประเทศมี 215 คน


## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
data_updated["announce_date"] = pd.to_datetime(data_updated["announce_date"] ,format="%d/%m/%Y") #แปลงข้อมูลให้เป็น datetime

In [ ]:
year_2021 = []
for i, row in data_updated.iterrows(): # ตัวแปรมารอรับสองค่า
  if row["announce_date"].year == 2021:
        year_2021.append(row)
data_2021 = pd.DataFrame(year_2021)
data_2021.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
124,125,2021-03-06,5/3/2021,หญิง,55.0,ปี,Thailand,ปทุมธานี,Cluster ตลาดพรพัฒน์,ปทุมธานี,ธัญบุรี
6885,6886,2021-01-01,31/12/2020,หญิง,40.0,ปี,Thailand,กรุงเทพมหานคร,Cluster สมุทรสาคร,ปทุมธานี,คลองหลวง
6886,6887,2021-01-01,31/12/2020,หญิง,21.0,ปี,Thailand,ปทุมธานี,Cluster ระยอง,ปทุมธานี,คลองหลวง
6887,6888,2021-01-01,31/12/2020,หญิง,20.0,ปี,Thailand,นครปฐม,สถานบันเทิง,นครปฐม,สามพราน
6888,6889,2021-01-01,31/12/2020,หญิง,47.0,ปี,Thailand,สมุทรสาคร,Cluster สมุทรสาคร,นครปฐม,สามพราน
